def jenkinsFile
pipeline {
    agent {label "wintest"}
    stages {
        stage('Load Jenkins File') {
            steps {
                script {
                    jenkinsFile = fileLoader.fromGit('tests/parallel_test/Jenkinsfile', 'https://github.com/taosdata/CiTest_TDengine.git', '2.4_test_1', 'ac1b45da-1f6f-469e-b617-c7e1d7e97b14', null, '')
                    jenkinsFile.start()
                }
            }
        }
        stage('windows test develop') {
            parallel {
                stage('build develop') {
                    steps {
                        sh '''
                            env
                            echo "build develop"
                            cd /var/lib
                            sh -c "echo \"$JOB_NAME" | grep -q Win; if [ $? -eq 0 ]; then echo \"OK\"; else echo \"$JOB_NAME\"; fi; pwd"
                        '''
                    }
                }
                stage('run test develop') {
                    agent {label "win"}
                    steps {
                        bat '''
                            echo "run win test develop"
                        '''
                    }
                }
            }
        }
        stage('windows test 2.4') {
            parallel {
                stage('build 2.4') {
                    steps {
                        sh '''
                            echo "build 2.4"
                        '''
                    }
                }
                stage('run test 2.4') {
                    agent {label "win"}
                    steps {
                        bat '''
                            echo "run win test 2.4"
                        '''
                    }
                }
            }
        }
        stage('windows test master') {
            parallel {
                stage('build master') {
                    steps {
                        sh '''
                            echo "build master"
                        '''
                    }
                }
                stage('run test master') {
                    agent {label "win"}
                    steps {
                        bat '''
                            echo "run win test master"
                        '''
                    }
                }
            }
        }
        stage('windows test 2.0') {
            parallel {
                stage('build 2.0') {
                    steps {
                        sh '''
                            echo "build 2.0"
                        '''
                    }
                }
                stage('run test 2.0') {
                    agent {label "win"}
                    steps {
                        bat '''
                            echo "run win test 2.0"
                        '''
                    }
                }
            }
        }
    }
    post {
        success {
            emailext (
                subject: " SUCCESSFUL: Windows Test ",
                body: """<p>SUCCESSFUL: Windows Test:</p>
                    <p>please check console output at "<a href="${env.BUILD_URL}">${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>"</p>""",
                to: "fztang@taosdata.com", 
                from: "support@taosdata.com"
            )
        }
        failure {
            emailext (
                subject: "FAILED: Windows Test",
                body: """<p>FAILED: Windows Test:</p>
                    <p>please check console output at "<a href="${env.BUILD_URL}">${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>"</p>""",
                to: "fztang@taosdata.com",
                from: "support@taosdata.com"
            )
        }
    }
}
